export class AD_CompanySettings {
  recID: String
  ;companyCode: String
  ;legalName: String
  ;legalName2: String
  ;shortName: String
  ;logoFull:string
  ;logo: string
  ;taxCode: String
  ;fiscalYear: String
  ;baseCurr: String
  ;secondCurr: String
  ;conversionCurr: String
  ;representative: String
  ;bankAccount: String
  ;street: String
  ;city: String
  ;countryID: String
  ;provinceID: String
  ;districtID: String
  ;postalCode: String
  ;regionID: String
  ;timeZone: any
  ;contactName: String
  ;jobTitle: String
  ;phone: String
  ;phoneExt: String
  ;faxNo: String
  ;mobile: String
  ;email: String
  ;personalEmail: String
  ;sms: String
  ;webPage: String
  ;version: Number
  ;versionOn: String
  ;lVEstimation: Boolean
  ;createdOn: Date
  ;createdBy: String
  ;modifiedOn: Date
  ;modifiedBy: String
  ;intergration: String
  ;storage: Number
  ;memory: Number
}
