export interface Item {
  itemID: string;
  itemName: string;
  itemName2: string;
  itemGroupID: string;
  itemType: string;
  assetGroupID: string;
  inventModelID: string;
  dimGroupID: string;
  productLineID: string;
  manufacturer: string;
  abcCategory: string;
  umid: string;
  dimConversion: boolean | null;
  conversionRule: string;
  sWeight: number;
  description: string;
  purchase: boolean;
  sales: boolean;
  production: boolean;
  costPrice: number;
  priceDeviation: number;
  cwItem: boolean;
  cwMulti: boolean;
  cwum: string;
  cwDeviation: number;
  warehouseID: string;
  locationID: string;
  underDelivery: number;
  overDelivery: number;
  shelfLife: number;
  bestBefore: number;
  packingUM: string;
  packingQty: number;
  nWeight: number;
  gWeight: number;
  length: number;
  width: number;
  height: number;
  palletType: string;
  palletQty: number;
  layers: number;
  coneType: string;
  minSettledQty: number;
  barcodeControl: string;
  barcodeStyle: string;
  diM2: string;
  diM3: string;
  alterItemID: string;
  stop: boolean;
  owner: string;
  buid: string;
  industries: string;
  createdOn: string;
  createdBy: string;
  modifiedOn: string | null;
  modifiedBy: string;
  note: string;
  cwConversion: number | null;
  sizeID: string;
  packingSizeID: string;
  attributeID: string;
  colorID: string;
  autoConversion: boolean | null;
  conversionFormula: string;
  pWeight: number | null;
  userItemIDToCreateDim2: boolean | null;
}
