export interface IJournal {
  recID: string;
  journalNo: string;
  journalName: string;
  journalDesc: string;
  journalType: string;
  subType: string;
  postedLayer: string;
  fiscalYear: number | null;
  periodID: string;
  transCount: number;
  reasonID: string;
  status: string;
  voucherFormat: string;
  autoAssignRule: string;
  allowEdited: boolean;
  invoiceForm: string;
  currencyID: string;
  exchangeRate: number;
  fixedCurrency: boolean;
  cashBookID: string;
  warehouseIssue: string;
  warehouseReceipt: string;
  mixedPayment: boolean;
  subControl: string;
  settleControl: string;
  brigdeAcctControl: string;
  drAcctControl: string;
  drAcctID: string;
  crAcctControl: string;
  crAcctID: string;
  diM1Control: string;
  diM2Control: string;
  diM3Control: string;
  diM1: string;
  diM2: string;
  diM3: string;
  idimControl: string;
  isSettlement: boolean;
  projectControl: string;
  assetControl: string;
  loanControl: string;
  inputControl: string;
  productionControl: string;
  illegalControl: string;
  noteControl: string;
  vatControl: string;
  useDutyTax: boolean | null;
  useExciseTax: boolean | null;
  otherControl: string;
  approvalControl: string;
  approver: any;
  autoPost: any;
  unpostControl: boolean;
  unPostDays: number | null;
  exported: boolean;
  attachments: number | null;
  comments: number | null;
  stop: boolean;
  owner: string;
  buid: string;
  createdOn: string;
  createdBy: string;
  modifiedOn: string | null;
  modifiedBy: string;
  transLimit: number | null;
  transControl: string;
  transConfirmUser: string;
  exchangeType: string;
  multiCurrency: any;
  vatType: string;
  dataValue: string;
  checkImage: boolean;
  inputMode: string;
  postingMode: string;
  unbounds: any;
  autoNumber: string;
  postedDateControl: string;
}
