export class OKRs {
    RecID:string;
    Year:number;
    PeriodID:string;
    numbererval:string;
    Sorting:number;
    OKRLevel:string;
    OKRType:string;
    OKRName:string;
    Category:string;
    Confidence:string;
    Tags:string;
    Memo:string;
    Measurement:string;
    Timeline:string;
    Status:string;
    Progress:number;
    Weight:number;
    Current:number;
    Target:number;
    Actual:number;
    UMID:string;
    Plan:string;
    Frequence:string;
    CheckIn:string;
    CheckInMode:string;
    LastCheckIn:Date;
    Alignment:string;
    ParentID:string;
    ApproveControl:string;
    ApproveStatus:string;
    Note:string;
    KRs:number;
    Tasks:number;
    Attachments:number;
    Comments:number;
    AutoCreated:boolean;
    Stop:boolean;
    Targets:Targets[];
    CheckIns:CheckIns[];
    Shares:Shares[];
    Notes:object[];
    Updates:object[];
    Visibility:string;
    PositionID:string;
    OrgUnitID:string;
    DeptID:string;
    DivisionID:string;
    Owner:string;
    BUID:string;
    CreatedOn:Date;
    CreatedBy:string;
    ModifiedOn:Date;
    ModifiedBy:string;
  }
  export class Targets {
    RecID:string;
    OKRID:string;
    Period:string;
    PlanDate:Date;
    Target:number;
    Comment:string;
    CreatedOn:Date;
    CreatedBy:string;
    ModifiedOn:Date;
    ModifiedBy:string;
  }

  export class CheckIns{
    RecID:string;
    OKRID:string;
    OKRStatus:string;
    CheckIn:Date;
    Value:number;
    Status:string;
    Comment:string;
    PositionName:string;
    CreatedOn:Date;
    CreatedBy:string;
    ModifiedOn:Date;
    ModifiedBy:string;
  }
  export class Shares{
    RecID:string;
    ObjectType:string;
    ObjectID:string;
    Permission:string;
    Read:number;
    View:number;
    Write:number;
    Delete:number;
    Download:number;
    Upload:number;
    Share:number;
    StartedOn:Date;
    ExpiredOn:Date;
    Note:string;
    AutoCreated:boolean;
    CreatedOn:Date;
    CreatedBy:string;
    ModifiedOn:Date;
    ModifiedBy:string;
  }

  export class Links{
    RecID:string;
    OKRID:string;
    RefID:string;
    RefType:string;
    ObjectType:string;
    ObjectID:string;
    DistributePct:number;
    DistributeValue:number;
    Comment:string;
    CreatedOn:Date;
    CreatedBy:string;
    ModifiedOn:Date;
    ModifiedBy:string;
  }

