export interface ICashTransfer {
  recID: string;
  journalNo: string;
  journalType: string;
  subType: string;
  voucherNo: string;
  voucherDate: string;
  requester: string;
  cashBookID: string;
  bankAcctID: string;
  bankID: string;
  currencyID: string;
  exchangeRate: number;
  multi: boolean;
  totalAmt: number;
  totalAmt2: number;
  exchangeRate2: number;
  exchangeAmt: number;
  objectType: string;
  objectID: string;
  objectName: string;
  payeeID: string;
  payee: string;
  pmtMethodID: string;
  reasonID: string;
  memo: string;
  memo2: string;
  cashBookID2: string;
  status: string;
  statusCode: string;
  feeControl: any;
  fees: number;
  feeNote: string;
  cashAcctID: string;
  offsetAcctID: string;
  diM1: string;
  diM2: string;
  diM3: string;
  projectID: string;
  postedLayer: string;
  refType: string;
  refNo: string;
  refID: string | null;
  owner: string;
  buid: string;
  createdOn: string;
  createdBy: string;
  modifiedOn: string | null;
  modifiedBy: string;
  exchangeAmt2: number;

  unbounds?: any;
  cashBookName?: string;
}
