export interface IVATInvoice {
  recID: string;
  transID: string;
  lineID: string;
  rowNo: number;
  accountID: string;
  offsetAcctID: string;
  objectType: string;
  objectID: string;
  invoiceForm: string;
  invoiceSeri: string;
  invoiceNo: string;
  invoiceDate: string | null;
  invoiceDueDate: string | null;
  objectName: string;
  address: string;
  taxCode: string;
  buyer: string;
  goods: string;
  pmtMethodID: string;
  umid: string;
  quantity: number;
  unitPrice: number;
  taxBase: number;
  taxBase2: number;
  taxBase3: number;
  vatid: string;
  taxAmt: number;
  taxAmt2: number;
  taxAmt3: number;
  taxAcctID: string;
  taxNote: string;
  taxTransDate: string | null;
  currencyID: string;
  exchangeRate: number;
  multi: boolean;
  eInvoiceID: string;
  eInvoiceNo: string;
  selected: boolean;
  cancelled: boolean;
  cancelledReason: string;
  cancelledNote: string;
  cancelledRefNo: string;
  cancelledOn: string | null;
  cancelledBy: string;
  diM1: string;
  diM2: string;
  diM3: string;
  projectID: string;
  note: string;
  createdOn: string;
  createdBy: string;
  modifiedOn: string | null;
  modifiedBy: string;
}
