export const environment = {
  production: false,
  isDesign: false,
  mutiTenant: true,
  dfPe: '',
  appVersion: 'v101lv',
  TNKey: 'tnf649fc9a5f55',
  shopping: '',
  reportUrl: '',
  apiUrl: '',
  pdfUrl: '',
  urlUpload: '',
  office365: '',
  appName: '',
  saas: 1,

  SureMeet: {
    baseUrl: 'https://api.suremeet.vn/',
    tokenUrl: 'api/auth/token',
    addUpdateMeetingUrl: 'PublicMeeting/AddUpdate',
    connectMettingUrl: 'PublicMeeting/Verify',
    client_id: 'portal',
    client_secret: 'lacviet@2022@$%!$$!(@',
    app_id: 'demo.suremeet@gmail.com',
    app_secret: '123456',
  },
  firebase: {
    apiKey: 'AIzaSyC1SKqppxpxwT7i3qEdUjJjn-J_SMoUBic',
    authDomain: 'ermtest-2a9bb.firebaseapp.com',
    projectId: 'ermtest-2a9bb',
    storageBucket: 'ermtest-2a9bb.appspot.com',
    messagingSenderId: '319703529330',
    appId: '1:319703529330:web:d0569f86d85524c1ca0feb',
    measurementId: 'G-HH40VHYRF0',
  },
  FCMToken: '',
  IMGEXTENSION: ['png', 'jpeg', 'jpg', 'bmp']
};
