export interface IVoucherLineInvoice {
  recID: string;
  transID: string;
  lineID: string;
  lineType: string;
  rowNo: number;
  transactionText: string;
  accountID: string;
  offsetAcctID: string;
  objectType: string;
  objectID: string;
  dIM1: string;
  dIM2: string;
  dIM3: string;
  projectID: string;
  invoiceType: string;
  invoiceForm: string;
  invoiceSeri: string;
  invoiceNo: string;
  invoiceDate: string | null;
  invoiceDueDate: string | null;
  invoiceName: string;
  invoiceAddress: string;
  invoiceTaxCode: string;
  buyer: string;
  goods: string;
  pmtMethodID: string;
  pmtTermID: string;
  multi: boolean;
  vATID: string;
  uMID: string;
  quantity: number;
  unitPrice: number;
  taxBase: number;
  taxBase1: number;
  taxBase2: number;
  taxAmt: number;
  taxAmt1: number;
  taxAmt2: number;
  taxAcctID: string;
  taxNote: string;
  taxTransDate: string | null;
  currencyID: string;
  exchangeRate: number;
  eInvoiceID: string;
  eInvoiceNo: string;
  selected: boolean;
  cancelled: boolean;
  cancelledReason: string;
  cancelledNote: string;
  cancelledRefNo: string;
  cancelledOn: string | null;
  cancelledBy: string;
  note: string;
  createdOn: string;
  createdBy: string;
  modifiedOn: string | null;
  modifiedBy: string;
}
