export interface IPurchaseInvoice {
    recID: string;
    journalNo: string;
    journalType: string;
    voucherNo: string;
    voucherDate: string;
    voucherType: string;
    invoiceType: string;
    invoiceForm: string;
    invoiceSeri: string;
    invoiceNo: string;
    invoiceDate: string | null;
    invoiceDueDate: string | null;
    invoiceName: string;
    invoiceAdddess: string;
    invoiceTaxCode: string;
    objectType: string;
    objectID: string;
    currencyID: string;
    exchangeRate: number;
    multi: boolean;
    memo: string;
    memo2: string;
    status: string;
    validated: boolean;
    autoCreated: boolean;
    autoSettlement: string;
    settleID: string | null;
    settleVouchers: string;
    totalDR: number;
    totalCR: number;
    totalAmt: number;
    totalDiscPct: number;
    totalDiscAmt: number;
    totalDiscAllo: boolean;
    transactionType: string;
    warehouse: string;
    orderPoolID: string;
    contractNo: string;
    buyerGroupID: string;
    buyer: string;
    pmtMethodID: string;
    pmtTermID: string;
    pmtSchedID: string;
    cashDiscID: string;
    cashDiscDate: string | null;
    cashDiscPct: number;
    taxTransDate: string | null;
    taxExchRate: number;
    taxMulti: boolean;
    taxNote: string;
    thirdPartyID: string;
    thirdParty: string;
    returnReason: string;
    returnReference: string;
    returnNote: string;
    shipmentID: string | null;
    orderNo: string;
    orderer: string;
    refNo: string;
    refDate: string | null;
    bLNo: string;
    bLDate: string | null;
    diM1: string;
    diM2: string;
    diM3: string;
    projectID: string;
    printed: boolean;
    integration: boolean;
    owner: string;
    buid: string;
    approvedBy: string;
    approvedOn: string | null;
    createdOn: string;
    createdBy: string;
    postedLayer: string;
    postedOn: string | null;
    postedBy: string;
    modifiedOn: string | null;
    modifiedBy: string;

    unbounds: any;
}