export interface IPurchaseInvoiceLine {
    recID: string;
    transID: string;
    rowNo: number;
    lineType: string;
    lineStatus: string;
    itemID: string;
    lotID: string;
    idiMID: string;
    idiM0: string;
    idiM1: string;
    idiM2: string;
    idiM3: string;
    idiM4: string;
    idiM5: string;
    idiM6: string;
    idiM7: string;
    idiM8: string;
    idiM9: string;
    fixedDIMs: string;
    cwum: string;
    cwConversion: number;
    cwQty: number;
    cwPrice: boolean;
    umid: string;
    conversion: number;
    quantity: number;
    costPrice: number | null;
    costAmt: number;
    purcPrice: number;
    purcAmt: number | null;
    lineDiscPct: number;
    lineDiscAmt: number;
    totalDiscPct: number;
    totalDiscAmt: number;
    discPct: number;
    discAmt: number;
    netAmt: number;
    miscPrice: number;
    miscAmt: number;
    salesTaxPct: number;
    salesTaxAmt: number;
    exciseTaxPct: number;
    exciseTaxAmt: number;
    vatid: string;
    vatBase: number;
    vatPct: number | null;
    vatAmt: number;
    totalAmt: number | null;
    purcAmt2: number | null;
    discAmt2: number;
    netAmt2: number;
    miscAmt2: number;
    salesTaxAmt2: number;
    exciseTaxAmt2: number;
    vatBase2: number;
    vatAmt2: number;
    totalAmt2: number | null;
    vatBase3: number;
    vatAmt3: number;
    pmtTermID: string;
    diM1: string;
    diM2: string;
    diM3: string;
    projectID: string;
    reasonID: string;
    consumption: boolean;
    assetType: string;
    assetGroupID: string;
    serviceDate: string | null;
    servicePeriods: number | null;
    employeeID: string;
    siteID: string;
    inventAcctID: string;
    aPAcctID: string;
    note: string;
    refType: string;
    refNo: string;
    refID: string | null;
    refLotID: string | null;
    refLineID: string | null;
    registeredQty: number;
    deliveredQty: number;
    cwRegisteredQty: number;
    cwDeliveredQty: number;
    autoCreated: boolean;
    createdOn: string;
    createdBy: string;
    modifiedOn: string | null;
    modifiedBy: string;

    _rowIndex: any;
    unbounds?: any;
}