export class CM_Products {
  recID: string;
  productID: string;
  productName: string;
  productName2: string;
  businessLineID: string;
  parentID: string;
  note: string;
  sorting: number;
  stop: boolean;
  detail: string;
  onHand: number;
  sales: number;
  unit: string;
  unitPrice: number;
  currencyID: string;
  owner: string;
  bUID: string;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
}
export class CM_BusinessLines {
  recID: string;
  businessLineID: string;
  businessLineName: string;
  businessLineName2: string;
  parentID: string;
  note: string;
  sorting: number;
  stop: boolean;
  owner: string;
  bUID: string;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
}

export class CM_Quotations {
  recID: string;
  quotationID: string;
  quotationName: string;
  quotationName2: string;
  category: string;
  orderPoolID: string;
  customerID: string;
  salespersonID: string;
  consultantID: string;
  delTermID: string;
  delModeID: string;
  pmtTermID: string;
  pmtMethodID: string;
  currencyID: string;
  status: string;
  deadline: Date;
  memo: string;
  totalAmt: number;
  discPct: number;
  discAmt: number;
  tags: string;
  refType: string;
  refNo: string;
  refID: string;
  versionNo: string;
  revision: number;
  parentID: string;
  attachments: number;
  comments: number;
  owner: string;
  bUID: string;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
}

export class CM_Opportunities {
  recID: string;
  opportunityID: string;
  processID: string;
  productTypeID: string;
  campaignID: string;
  objectType: string;
  objectID: string;
  contacts: CM_Products[] = [];
  // opponents: objects;
  // products: objects;
  title: string;
  startDate: Date;
  endDate: Date;
  successRate: number;
  expectedRevenue: number;
  memo: string;
  status: string;
  attachments: number;
  comments: number;
  refType: string;
  refID: string;
  closed: boolean;
  closedOn: Date;
  owner: string;
  bUID: string;
  permissions: CM_Permissions[] = [];
  tags: string;
  stepID: string;
  // templates: objects;
  // datas: Json;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
  bit;
}

export class CM_Permissions {
  recID: string;
  roleType: string;
  objectType: string;
  objectName: string;
  objectID: string;
  create: boolean;
  read: boolean;
  update: boolean;
  assign: boolean;
  delete: boolean;
  share: boolean;
  upload: boolean;
  download: boolean;
  note: string;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
  edit: boolean;
  allowPermit: boolean;
  publish: boolean;
  isActive: boolean;
  startDate: Date;
  endDate: Date;
  approvalRule: string;
  approverType: string;
  approvers: string;
  approvedBy: string;
  approveStatus: string;
  approvedOn: Date;
  autoCreate: string;
  allowUpdateStatus: string;
}

export class CM_Customers {
  recID: string;
  customerID: string;
  customerName: String;
  customerName2: String;
  shortName: String;
  taxCode: String;
  custGroupID: String;
  industries: String;
  segmentID: String;
  channelID: String;
  address: String;
  phone: String;
  faxNo: String;
  email: String;
  webPage: String;
  establishDate: Date;
  headcounts: number;
  annualRevenue: number;
  workingDays: String;
  officialHour: boolean;
  countryID: String;
  provinceID: String;
  districtID: String;
  regionID: String;
  consultantID: String;
  invoiceAccount: String;
  isBlackList: boolean;
  stop: boolean;
  stopReason: String;
  customerFrom: Date;
  customerResource: string;
  bankAccount: string;
  bankName: string;
  memo: string;
  owner: String;
  bUID: String;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
}

export class CM_Contacts {
  recID: string;
  contactID: string;
  contactName: string;
  contactType: string;
  category: String;
  firstName: String;
  lastName: String;
  gender: String;
  salutation: String;
  birthday: Date;
  birthPlace: String;
  iDCardNo: String;
  issuedOn: Date;
  issuedBy: String;
  maritalStatus: String;
  nationality: String;
  ethnicGroup: String;
  religion: String;
  education: String;
  occupation: String;
  jobTitle: String;
  department: String;
  income: number;
  bankAcctNo: String;
  bankID: String;
  birthAddress: String;
  address: String;
  countryID: String;
  provinceID: String;
  districtID: String;
  wardID: String;
  postalCode: String;
  mobile: String;
  phone: String;
  phoneExt: String;
  email: String;
  personalEmail: String;
  webPage: String;
  objectType: String;
  objectID: String;
  objectName: String;
  cumulatedPoints: number;
  loyaltyGroupID: String;
  vIP: boolean;
  isDefault: boolean;
  note: String;
  stop: boolean;
  userID: String;
  allowCall: boolean;
  allowEmail: boolean;
  owner: String;
  bUID: String;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
}
