export class CM_Products {
  recID: string;
  productID: string;
  productName: string;
  productName2: string;
  businessLineID: string;
  parentID: string;
  note: string;
  sorting: number;
  stop: boolean;
  detail: string;
  onHand: number;
  sales: number;
  unit: string;
  unitPrice: number;
  currencyID: string;
  owner: string;
  bUID: string;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
  write: boolean = true;
  download: boolean = true;
  delete: boolean = true;
  share: boolean = true;
  read: boolean = true;
}
export class CM_BusinessLines {
  recID: string;
  businessLineID: string;
  businessLineName: string;
  businessLineName2: string;
  parentID: string;
  note: string;
  sorting: number;
  stop: boolean;
  owner: string;
  bUID: string;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
}

export class CM_Quotations {
  recID: string;
  quotationID: string;
  quotationName: string;
  quotationName2: string;
  category: string;
  orderPoolID: string;
  customerID: string;
  salespersonID: string;
  consultantID: string;
  delTermID: string;
  delModeID: string;
  pmtTermID: string;
  pmtMethodID: string;
  currencyID: string;
  status: string = '1';
  deadline: Date;
  memo: string;
  totalAmt: number;
  discPct: number;
  discAmt: number;
  tags: string;
  refType: string;
  refNo: string;
  refID: string;
  versionNo: string;
  revision: number;
  parentID: string;
  attachments: number;
  comments: number;
  owner: string;
  bUID: string;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
}

export class CM_QuotationsLines {
  recID: string;
  transID: string;
  rowNo: number;
  lineType: string;
  lineStatus: string;
  barcode: string;
  itemID: string;
  itemNote: string;
  iDIM0: string;
  iDIM1: string;
  iDIM2: string;
  iDIM3: string;
  iDIM4: string;
  quantity: number;
  uMID: string;
  conversion: number;
  cWUM: string;
  cWConversion: number;
  cWQty: number;
  cWOnhand: number;
  onhand: number;
  costPrice: number;
  costAmt: number;
  stdPrice: number;
  salesPrice: number;
  salesAmt: number;
  discPct: number;
  discAmt: number;
  netAmt: number;
  commissionPct: number;
  commissionAmt: number;
  salesTaxPct: number;
  salesTaxAmt: number;
  exciseTaxPct: number;
  exciseTaxAmt: number;
  vATID: string;
  vATBase: number;
  vATAmt: number;
  refType: string;
  refNo: string;
  refID: string;
  refLineID: string;
  note: string;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
}

export class CM_Deals {
  recID: string;
  dealID: string;
  dealName: string;
  dealName2: string;
  category: string;
  customerID: string;
  channelID: string;
  campaignID: string;
  businessLineID: string;
  memo: string;
  tags: string;
  dealValue: number;
  probability: number;
  expectedClosed: number;
  status: string;
  statusCodeID: string;
  stepID: string;
  nextStep: string;
  lastUpdated: Date;
  closed: boolean;
  closedOn: Date;
  closedBy: string;
  closeReason: string;
  closeComment: string;
  refType: string;
  refNo: string;
  refID: string;
  attachments: number;
  comments: number;
  salespersonID: string;
  consultantID: string;
  processID: string;
  startDate: Date;
  endDate: Date;
  // datas: Json; hỏi kiểu dữ liệu sau
  owner: string;
  bUID: string;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
  boolean;
}

export class CM_Permissions {
  recID: string;
  roleType: string;
  objectType: string;
  objectName: string;
  objectID: string;
  create: boolean;
  read: boolean;
  update: boolean;
  assign: boolean;
  delete: boolean;
  share: boolean;
  upload: boolean;
  download: boolean;
  note: string;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
  edit: boolean;
  allowPermit: boolean;
  publish: boolean;
  isActive: boolean;
  startDate: Date;
  endDate: Date;
  approvalRule: string;
  approverType: string;
  approvers: string;
  approvedBy: string;
  approveStatus: string;
  approvedOn: Date;
  autoCreate: string;
  allowUpdateStatus: string;
}

export class CM_Customers {
  recID: string;
  customerID: string;
  customerName: string;
  customerName2: string;
  shortName: string;
  taxCode: string;
  custGroupID: string;
  industries: string;
  segmentID: string;
  channelID: string;
  address: string;
  phone: string;
  faxNo: string;
  email: string;
  webPage: string;
  establishDate: Date;
  headcounts: string;
  annualRevenue: number;
  workingDays: string;
  officialHour: boolean;
  countryID: string;
  provinceID: string;
  districtID: string;
  regionID: string;
  consultantID: string;
  invoiceAccount: string;
  isBlackList: boolean;
  stop: boolean;
  stopReason: string;
  customerFrom: Date;
  customerResource: string;
  bankAccount: string;
  bankID: string;
  memo: string;
  tags: string;
  owner: string;
  bUID: string;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
}

export class CM_Contacts {
  recID: string;
  contactID: string;
  contactName: string;
  contactType: string;
  category: string;
  firstName: string;
  lastName: string;
  gender: string;
  salutation: string;
  birthday: Date;
  birthPlace: string;
  iDCardNo: string;
  issuedOn: Date;
  issuedBy: string;
  maritalStatus: string;
  nationality: string;
  ethnicGroup: string;
  religion: string;
  education: string;
  occupation: string;
  jobTitle: string;
  department: string;
  income: number;
  bankAccount: string;
  bankID: string;
  birthAddress: string;
  address: string;
  countryID: string;
  provinceID: string;
  districtID: string;
  wardID: string;
  postalCode: string;
  mobile: string;
  phone: string;
  phoneExt: string;
  email: string;
  personalEmail: string;
  webPage: string;
  objectType: string;
  objectID: string;
  objectName: string;
  cumulatedPonumbers: number;
  loyaltyGroupID: string;
  vIP: boolean;
  isDefault: boolean;
  memo: string;
  stop: boolean;
  userID: string;
  allowCall: boolean;
  allowEmail: boolean;
  tags: string;
  owner: string;
  bUID: string;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
}

export class BS_AddressBook {
  recID: string;
  adressType: string;
  adressName: string;
  objectType: string;
  objectID: string;
  street: string;
  city: string;
  countryID: string;
  provinceID: string;
  districtID: string;
  postalCode: string;
  regionID: string;
  timeZone: string;
  longitude: string;
  latitude: string;
  distance: string;
  primaryContact: string;
  secondContact: string;
  phone: string;
  phoneExt: string;
  faxNo: string;
  mobile: string;
  email: string;
  sMS: string;
  webPage: string;
  delRouteID: string;
  calendarID: string;
  numbererval: string;
  duration: string;
  lastUpdated: Date;
  note: string;
  stop: boolean;
  isDefault: boolean;
  createdOn: Date;
  createdBy: string;
  modifiedOn: Date;
  modifiedBy: string;
  owner: string;
  bUID: string;
  employeeID: string;
  positionID: string;
  orgUnitID: string;
  divisionID: string;
  wardID: string;
}
export class CM_Contracts {
recID:string;
contractID:string;
contractDate:Date;
contractName:string;
contractType:string;
category:string;
assetID:string;
projectID:string;
quotationID:string;
orderID:string;
objectType:string;
objectID:string;
objectName:string;
contactID:string;
customerID:string;
currencyID:string;
exchangeRate:number;
contractAmt:number;
VATID:string;
paymentStatus:string;
paidAmt:number;
remainAmt:number;
memo:string;
status:string;
periods:number;
numbererval:string;
effectiveFrom:Date;
effectiveTo:Date;
extendOn:Date;
disposalOn:Date;
warantyMonths:number;
warantyExpired:Date;
salespersonID:string;
consultantID:string;
pmtMethodID:string;
delModeID:string;
delTermID:string;
parentID:string;
refType:string;
refID:string;
refNo:string;
attachments:number;
note:string;
stop:boolean;
owner:string;
bUID:string;
createdOn:Date;
createdBy:string;
modifiedOn:Date;
}
