import { Type } from '@angular/core';
import { FiscalPeriodsComponent } from './settings/fiscal-periods/fiscal-periods.component';
import { FiscalPeriodsAutoCreateComponent } from './settings/fiscal-periods/fiscal-periods-add/fiscal-periods-auto-create.component';
import { PopAddVatpostingComponent } from './settings/vatcodes/pop-add-vatposting/pop-add-vatposting.component';

export const T_Comp: Type<any>[] = [
  CurrencyComponent,
  CurrencyAddComponent,
  ExchangeRateSettingAddComponent,
  ExchangerateAddComponent,
  AccountsComponent,
  AccountsAddComponent,
  CustomersComponent,
  CustomersAddComponent,
  BankAddComponent,
  ContactAddComponent,
  AddressAddComponent,
  VendorsComponent,
  VendorsAddComponent,
  NosubAsideComponent,
  ItemsComponent,
  ItemsAddComponent,
  ItemsSizeAddComponent,
  ItemsStyleAddComponent,
  ItemsColorAddComponent,
  WarehousesComponent,
  WarehousesAddComponent,
  UnitsofmearsureComponent,
  UnitsOfMearSureAdd,
  ConversionAddComponent,
  InventoryComponent,
  PopAddInventoryComponent,
  ItempostingaccountsComponent,
  DimensionGroupsComponent,
  PopAddDimensionGroupsComponent,
  ItemsConversionAddComponent,
  PopAddDimensionSetupComponent,
  ArPostingAccountsComponent,
  PopAddArComponent,
  APPostingAccountsComponent,
  PopupAddAPPostingAccountComponent,
  PostingAccountsAddComponent,
  FAPostingAccountsComponent,
  PopupAddFAPostingAccountComponent,
  FixedAssetsComponent,
  PopupAddFixedAssetComponent,
  FiscalPeriodsComponent,
  PopAddFiscalPeriodsComponent,
  ItemBatchsComponent,
  PopAddItemBatchsComponent,
  ItemSeriesComponent,
  PopAddItemSeriesComponent,
  VATCodesComponent,
  PopAddVatcodesComponent,
  PopAddVatpostingComponent,
  FiscalPeriodsAutoCreateComponent,
];
