import { Util } from "codx-core";

export class CashPaymentLine {
  accountID: any;
  assetGroupID: any;
  assetType: any;
  assign: any;
  autoCreated: any;
  cR2: any = 0;
  cr: any = 0;
  createdBy: any;
  createdOn: any;
  dR2: any = 0;
  delete: any;
  derpModelID: any;
  diM1: any;
  diM2: any;
  diM3: any;
  dr: any = 0;
  illegalExpense: any;
  includeTables: any;
  isBrigdeAcct: any;
  modifiedBy: any;
  modifiedOn: any;
  note: any;
  objectID: any;
  objectType: any;
  offsetAcctID: any;
  projectID: any;
  reasonID: any;
  recID: any = Util.uid();
  refLineID: any;
  refNo: any;
  rowNo: any;
  settledID: any;
  settledNo: any;
  settlementRule: any;
  share: any;
  subLGType: any;
  vatAmt: any = 0;
  vatAmt2: any = 0;
  transID: any;
  unbounds: any;
  singleEntry:any;
  updateColumns: any;
  vatid: any;
  write: any;
}
