export class CashPayment {
    address: any
    allowEditKey: any
    approvalRule: any
    approvedBy: any
    approvedOn: any
    assign: any
    bankAccount: any
    bankAcctNo: any
    bankID: any
    buid: any
    cashBookID: any
    createdBy: any
    createdOn: any
    currencyID: any
    delete: any
    exchangeRate: any
    id: any
    idCardNo: any
    idField: any
    illegalExpense: any
    includeTables: any
    invoiceControl: any
    isSettlement: any
    isTransfer: any
    issuedBy: any
    issuedOn: any
    journalNo: any
    journalType: any
    memo: any
    memo2: any
    mixedPayment: any
    modifiedBy: any
    modifiedOn: any
    multi: any
    objectID: any
    objectType: any
    owner: any
    payee: any
    paymentAmt: any
    paymentMethod: any
    paymentRequest: any
    pmtMethodID: any
    postedBy: any
    postedLayer: any
    postedOn: any
    recID: any
    receivableAccount: any
    receivableObject: any
    refID: any
    refNo: any
    refType: any
    share: any
    status: any
    totalCR: any
    totalDR: any
    transactionText: any
    unbounds: any
    updateColumns: any
    validated: any
    vendor: any
    voucherDate: any
    voucherNo: any
    voucherTime: any
    voucherType:any
    write: any
}