export class Inventorymodels {
  accountControl: any;
  allowEditKey: any;
  assign: any;
  buid: any;
  checkOnhand: any;
  createdBy: any;
  createdOn: any;
  delete: any;
  expiredDays: any;
  id: any;
  idField: any;
  includeTables: any;
  inventCosting: any;
  inventModelID: any;
  inventModelName: any;
  inventModelName2: any;
  modifiedBy: any;
  modifiedOn: any;
  nagetiveFinancial: any;
  nagetivePhysical: any;
  owner: any;
  postFinancial: any;
  postPhysical: any;
  qualityControl: any;
  quarantineControl: any;
  requirePick:any;
  requireRegister: any;
  reserveExpired: boolean = false;
  reserveMethod:boolean = false;
  reserveOrdered: boolean = false;
  reservePartial:boolean = false;
  reserveRule: any;
  reserveSameBatch: any;
  reserveUnavailable: any;
  share: any;
  stdCostIssue: any;
  stdCostReceipt: any;
  stop: any;
  unbounds: any;
  unpostFinancial: any;
  unpostPhysical: any;
  updateColumns: any;
  write: any;
}
