import { Util } from "codx-core";

export class PurchaseInvoicesLines {
  activityID: any;
  assetGroupID: any;
  assetID: any;
  assetTransType: any;
  assetType: any;
  autoCreated: boolean = false;
  consumption: any;
  conversion: any = 0;
  costAmt: any = 0;
  createdBy: any;
  createdOn: any;
  cwConversion: any = 0;
  cwPrice: boolean = false;
  cwQty: any = 0;
  cwRegisteredQty: any;
  cwReturnQty: any;
  cwum: any;
  derpModelID: any;
  diM1: any;
  diM2: any;
  diM3: any;
  discAmt: any = 0;
  discAmt2: any = 0;
  discPct: any = 0;
  employeeID: any;
  exciseTaxAmt: any = 0;
  exciseTaxAmt2: any;
  exciseTaxPct: any = 0;
  faLocationID: any;
  fixedDIMs: any;
  idiMany: any;
  idiM0: any;
  idiM1: any;
  idiM2: any;
  idiM3: any;
  idiM4: any;
  idiM5: any;
  idiM6: any;
  idiM7: any;
  idiM8: any;
  idiM9: any;
  idimid: any = Util.uid();
  ieTypeID: any;
  inventAcctID: any;
  itemID: any;
  itemName:any;
  lineDiscAmt: any = 0;
  lineDiscPct: any = 0;
  lineStatus: any;
  lineType: any;
  lotID: any = Util.uid();
  miscCharge: any;
  miscCharge2: any;
  miscChargePrice: any;
  modifiedBy: any;
  modifiedOn: any;
  multiDiscAmt: any;
  multiDiscPct: any;
  netAmt: any = 0;
  netAmt2: any = 0;
  note: any;
  offsetAcctID: any;
  onhand: any;
  rowNo:any;
  placeInService: any;
  placeInServiceDate: any;
  pmtTermID: any;
  projectID: any;
  purcAllocation: any;
  quantity: any = 0;
  recID: any = Util.uid();
  refID: any;
  refLineNo: any;
  refLotID: any;
  refNo: any;
  refTransID: any;
  refTransNo: any;
  refType: any;
  registeredQty: any;
  returnCostPrice: any;
  returnLotID: any;
  returnQty: any;
  returnReason: any;
  salesTaxAmt: any = 0;
  salesTaxAmt2: any = 0;
  salesTaxPct: any = 0;
  scrap: any;
  scrapReason: any;
  totalDiscAmt: any = 0;
  totalDiscPct: any = 0;
  transID: any;
  umid: any;
  unitPrice: any;
  updateColumn: any;
  vatAmt: any;
  vatAmt2: any;
  vatAmt3: any = 0;
  vatBase: any = 0;
  vatBase2: any = 0;
  vatBase3: any = 0;
  vatid: any;
  purcPrice:any = 0;
  purcAmt:any = 0;
  purcAmt2:any = 0;
  miscPrice:any = 0;
  miscAmt:any = 0;
  miscAmt2:any = 0;
}
