import { Util } from "codx-core";

export class IPurchaseInvoiceLine {
  recID: any = Util.uid();
  transID: any;
  rowNo: any;
  lineType: any;
  lineStatus: any;
  itemID: any;
  lotID: any = Util.uid();
  idiMID: any = Util.uid();
  idiM0: any;
  idiM1: any;
  idiM2: any;
  idiM3: any;
  idiM4: any;
  idiM5: any;
  idiM6: any;
  idiM7: any;
  idiM8: any;
  idiM9: any;
  fixedDIMs: any;
  cwum: any;
  cwConversion: number;
  cwQty: number;
  cwPrice: boolean;
  umid: string;
  conversion: number;
  quantity: number;
  costPrice: number | null;
  costAmt: number;
  purcPrice: number;
  purcAmt: number | null;
  lineDiscPct: number;
  lineDiscAmt: number;
  totalDiscPct: number;
  totalDiscAmt: number;
  discPct: number;
  discAmt: number;
  netAmt: number;
  miscPrice: number;
  miscAmt: number;
  salesTaxPct: number;
  salesTaxAmt: number;
  exciseTaxPct: number;
  exciseTaxAmt: number;
  vatid: string;
  vatBase: number;
  vatPct: number | null;
  vatAmt: number;
  totalAmt: number | null;
  purcAmt2: number | null;
  discAmt2: number;
  netAmt2: number;
  miscAmt2: number;
  salesTaxAmt2: number;
  exciseTaxAmt2: number;
  vatBase2: number;
  vatAmt2: number;
  totalAmt2: number | null;
  vatBase3: number;
  vatAmt3: number;
  pmtTermID: string;
  diM1: string;
  diM2: string;
  diM3: string;
  projectID: string;
  reasonID: string;
  consumption: boolean;
  assetType: string;
  assetGroupID: string;
  serviceDate: string | null;
  servicePeriods: number | null;
  employeeID: string;
  siteID: string;
  inventAcctID: string;
  aPAcctID: string;
  note: string;
  refType: string;
  refNo: string;
  refID: string | null;
  refLotID: string | null;
  refLineID: string | null;
  registeredQty: number;
  deliveredQty: number;
  cwRegisteredQty: number;
  cwDeliveredQty: number;
  autoCreated: boolean;
  createdOn: Date;
  createdBy: string;
  modifiedOn: string | null;
  modifiedBy: string;
  _rowIndex: any;
  unbounds?: any;
}
