export class SettledInvoices {
  accountID: any;
  balExchDiff: any;
  balanceAmt: any;
  balanceAmt2: any;
  cashDisc: any;
  cashDisc2: any;
  cashDiscID: any;
  consultantID: any;
  contractID: any;
  createdBy: any;
  createdOn;
  currencyID: any;
  diM1: any;
  diM2: any;
  diM3: any;
  discDate:any;
  dueDate : any;
  exchangeDiff: any;
  exchangeRate: any;
  exchangeReverse: any;
  installmentNo: any;
  invoiceDate : any;
  invoiceNo: any;
  isAdvance: any;
  lineID: any;
  loanContractID: any;
  modifiedBy: any;
  modifiedOn: any;
  multi: any;
  note: any;
  objectID: any;
  objectType: any;
  orderNo: any;
  orderType: any;
  penny: any;
  penny2: any;
  pmtMethodID: any;
  pmtTermID: any;
  productLineID: any;
  projectID: any;
  recID: any;
  rowNo: any;
  salespersonID: any;
  settledAmt: any;
  settledAmt2: any;
  settledDisc: any;
  settledDisc2: any;
  settledID: any;
  settledNo: any;
  settlementRule: any;
  transID: any;
}
