import { Util } from 'codx-core';

export class VATInvoices {
  recID: any = Util.uid();
  transID: any;
  lineID: any;
  rowNo: any;
  selected: any;
  invoiceType: any;
  invoiceForm: any;
  invoiceSeri: any;
  invoiceNo: any;
  invoiceDate: any = new Date();
  dueDate: any;
  objectType: any;
  objectID: any;
  objectName: any;
  address: any;
  taxCode: any;
  buyer: any;
  pmtMethodID: any;
  exchangeRate2: any;
  multi: any;
  goods: any;
  umid: any;
  quantity: any;
  unitPrice: any;
  vatBase: any = 0;
  vatid: any;
  vatPct: any;
  vatAmt: any = 0;
  vatBase2: any = 0;
  vatAmt2: any = 0;
  vatBase3: any = 0;
  vatAmt3: any = 0;
  vatAcctID: any;
  accountID: any;
  offsetAcctID: any;
  diM1: any;
  diM2: any;
  diM3: any;
  projectID: any;
  note: any;
  eInvoiceID: any;
  eInvoiceNo: any;
  cancelled: any;
  cancelledNote: any;
  cancelledReason: any;
  createdBy: any;
  createdOn: any;
  modifiedBy: any;
  modifiedOn: any;
}
