export class VATInvoices {
  accountID: any;
  address: any;
  buyer: any;
  cancelled: any;
  cancelledBy: any;
  cancelledNote: any;
  cancelledOn: any;
  cancelledReason: any;
  cancelledRefNo: any;
  createdBy: any;
  createdOn: any;
  currencyID: any;
  diM1: any;
  diM2: any;
  diM3: any;
  eInvoiceID: any;
  eInvoiceNo: any;
  exchangeRate: any;
  goods: any;
  invoiceDate: any = new Date();
  invoiceDueDate: any;
  invoiceForm: any;
  invoiceNo: any;
  invoiceSeri: any;
  lineID: any;
  modifiedBy: any;
  modifiedOn: any;
  multi: any;
  note: any;
  objectID: any;
  objectName: any;
  objectType: any;
  offsetAcctID: any;
  pmtMethodID: any;
  projectID: any;
  quantity: any;
  recID: any;
  rowNo: any;
  selected: any;
  taxAcctID: any;
  taxAmt: any;
  taxAmt2: any;
  taxAmt3: any;
  taxBase: any;
  taxBase2: any;
  taxBase3: any;
  taxCode: any;
  taxNote: any;
  taxTransDate: any;
  transID: any;
  umid: any;
  unitPrice: any;
  isTaxDetail:any;
  vatid:any;
  updateColumn: any;
}
