export interface IVATInvoice {
    recID: string;
    transID: string;
    lineID: string;
    rowNo: number;
    selected: boolean;
    invoiceType: string;
    invoiceForm: string;
    invoiceSeri: string;
    invoiceNo: string;
    invoiceDate: string | null;
    dueDate: string | null;
    objectType: string;
    objectID: string;
    objectName: string;
    address: string;
    taxCode: string;
    buyer: string;
    pmtMethodID: string;
    exchangeRate2: number;
    multi: boolean;
    goods: string;
    umid: string;
    quantity: number;
    unitPrice: number;
    vatBase: number;
    vatid: string;
    vatPct: number | null;
    vatAmt: number;
    vatBase2: number;
    vatAmt2: number;
    vatBase3: number;
    vatAmt3: number;
    vatAcctID: string;
    accountID: string;
    offsetAcctID: string;
    diM1: string;
    diM2: string;
    diM3: string;
    projectID: string;
    note: string;
    eInvoiceID: string;
    eInvoiceNo: string;
    cancelled: boolean;
    cancelledReason: string;
    cancelledNote: string;
    createdOn: Date;
    createdBy: string;
    modifiedOn: string | null;
    modifiedBy: string;
}