export interface ISalesInvoice {
  recID: string;
  journalNo: string;
  journalType: string;
  voucherNo: string;
  voucherDate: string;
  invoiceType: string;
  invoiceForm: string;
  invoiceSeriNo: string;
  invoiceNo: string;
  invoiceDate: string;
  invoiceDueDate: string | null;
  objectType: string;
  objectID: string;
  currencyID: string;
  exchangeRate: number;
  multi: boolean;
  memo: string;
  memo2: string;
  status: string;
  autoCreated: boolean;
  settleVouchers: string;
  totalAmt: number;
  totalDiscPct: number;
  totalDiscAmt: number;
  fixedCost: boolean;
  orderPoolID: string;
  salespersonID: string;
  delModeID: string;
  pmtMethodID: string;
  pmtTermID: string;
  vatAmt2: number;
  vatAmt3: number;
  taxExchRate: number;
  taxMulti: boolean;
  cancelled: string;
  cancelReason: string;
  cancelRefNo: string;
  cancelRefDate: string | null;
  cancelNote: string;
  orderNo: string;
  refID: string | null;
  refNo: string;
  diM1: string;
  diM2: string;
  projectID: string;
  printed: boolean;
  eInvoiceID: string;
  owner: string;
  bUID: string;
  createdOn: string;
  createdBy: string;
  postedLayer: string;
  modifiedOn: string | null;
  modifiedBy: string;
  objectName: string;
  postedDate: string | null;
  subType: string;
  address: string;
  taxCode: string;
  partnerID: string;
  warehouseID: string;
  reasonID: string;
  consultantID: string;
  contractID: string;
  settlement: string;
  refType: string;
  sendMail: string;
  sendSMS: string;
}
