export interface IAsset {
  assetID: string;
  assetName: string;
  assetName2: string;
  searchName: string;
  assetCardNo: string;
  assetType: string;
  assetGroupID: string;
  parentID: string;
  subStatus: string;
  status: string;
  deprGroupID: string;
  deprModelID: string;
  assetCategory: string;
  attributeGroupID: string;
  countingGroupID: string;
  maintainGroupID: string;
  maintenanceItems: string;
  employeeID: string;
  locationID: string;
  locationType: string;
  lastChangeOn: string | null;
  fuel: string;
  capacityUnit: string;
  capacityPrice: number;
  capacityUsed: number;
  designedCapacity: number;
  estimatedCapacity: number;
  lastUpdatedOn: string | null;
  acquisitionDate: string | null;
  acquisitionNo: string;
  uMID: string;
  quantity: number;
  multiQuantity: boolean;
  purcAmount: number;
  purcInvoiceNo: string;
  purcInvoiceDate: string | null;
  vendor: string;
  assetOriginID: string;
  transactionText: string;
  transactionNote: string;
  secondHand: boolean;
  leasing: boolean;
  borrowing: boolean;
  expiredOn: string | null;
  depreciation: boolean;
  costAmt: number;
  costAdjustement: number;
  accumulatedDepr: number;
  salvage: number;
  serviceYears: number;
  servicePeriods: number;
  deprPeriods: number;
  remainLife: number;
  deprCalendar: string;
  interval: string;
  deprMethod: string;
  deprConvention: string;
  deprRate: number;
  deprFactor: number;
  deprAdjustment: string;
  deprRateID: string;
  deprAllocation: string;
  adjustedPeriods: number;
  retainDepr: number;
  retainAllocation: string;
  fullDepreciation: boolean;
  switchtoSL: boolean;
  postedLayer: string;
  postLG: boolean;
  placeInService: string | null;
  deprStartDate: string | null;
  lastDeprDate: string | null;
  lastStatusDate: string | null;
  disposalDate: string | null;
  disposalAmt: number;
  disposalInvoiceNo: string;
  disposalTransID: string | null;
  assetAcctID: string;
  deprAcctID: string;
  expenseAcctID: string;
  diM1: string;
  diM2: string;
  diM3: string;
  projectID: string;
  objectType: string;
  objectID: string;
  realty: boolean;
  area: string;
  place: string;
  zone: string;
  aisle: string;
  floor: string;
  plot: string;
  direction: string;
  seriNo: string;
  model: string;
  modelYear: string;
  manufacturer: string;
  madeIn: string;
  note: string;
  itemID: string;
  iDIM0: string;
  iDIM1: string;
  iDIM2: string;
  iDIM3: string;
  salesStatus: string;
  salesPrice: number;
  contractNo: string;
  assetImage: string;
  assetPicture: string;
  barcode: string;
  barcodeStyle: string;
  longitude: number;
  latitude: number;
  insuranceMadatory: boolean;
  warrantyDate: string | null;
  maintenanceDays: number;
  lastMaintenance: string | null;
  lastChangedDate: string | null;
  splitedDate: string | null;
  splitedAssetID: string;
  splitedReason: string;
  splitedNote: string;
  refType: string;
  refID: string | null;
  refLotID: string | null;
  refNo: string;
  attachment: string;
  owner: string;
  buid: string;
}
